version: '3.2'
services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=booklib
      - POSTGRES_USER=booklib
      - POSTGRES_PASSWORD=booklib
      - PGDATA=/var/lib/pg_data
      - TZ=Asia/Jakarta
    ports:
      - "5656:5432"
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data
    