basePath: /api/v1
definitions:
  internal_handler_http_book.AddBookRequest:
    properties:
      author:
        type: string
      title:
        type: string
      year:
        type: integer
    type: object
  internal_handler_http_book.UpdateBookRequest:
    properties:
      author:
        type: string
      title:
        type: string
      year:
        type: integer
    type: object
  internal_handler_http_url-processor.ProcessUrlRequest:
    properties:
      operation:
        type: string
      url:
        type: string
    type: object
info:
  contact:
    email: support@rzndwb.xyz
    name: API Support
    url: http://booklib.rzndwb.xyz/support
  description: This is Book Library API.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://booklib.rzndwb.xyz/terms/
  title: BookLib API
  version: "1.0"
paths:
  /books:
    get:
      consumes:
      - application/json
      description: Returns a list of all books
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get all books
      tags:
      - books
    post:
      consumes:
      - application/json
      description: Creates a new book and returns success status
      parameters:
      - description: Book to create
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/internal_handler_http_book.AddBookRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add a new book
      tags:
      - books
  /books/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes a book with the given ID
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a book by ID
      tags:
      - books
    get:
      consumes:
      - application/json
      description: Returns a single book by its ID
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a book by ID
      tags:
      - books
    put:
      consumes:
      - application/json
      description: Updates the details of a book
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated book data
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/internal_handler_http_book.UpdateBookRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update an existing book
      tags:
      - books
  /process-url:
    post:
      consumes:
      - application/json
      description: Cleans or modifies a URL based on the specified operation.
      parameters:
      - description: URL processor request payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handler_http_url-processor.ProcessUrlRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Processed URL returned
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Clean and process a URL
      tags:
      - URLProcessor
swagger: "2.0"
